"""Render identical content through multiple PDF engines for quality comparison.

Uses the JSON content already generated by llm_comparison.py (from Claude Sonnet 5).

Run:
    python examples/pdf_comparison.py

Output (examples/output/):
    comparison_precision.pdf   - Emboss
    comparison_reportlab.pdf   - ReportLab
    comparison_weasyprint.pdf  - WeasyPrint
    comparison_fpdf2.pdf       - FPDF2
    comparison_report.txt      - Side-by-side feature/size comparison
"""

import json
import time
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

OUTPUT = Path(__file__).parent / "output"
OUTPUT.mkdir(exist_ok=True)

CONTENT_PATH = OUTPUT / "llm_content.json"


def load_content() -> dict:
    if not CONTENT_PATH.exists():
        print("Run llm_comparison.py first to generate content.")
        sys.exit(1)
    return json.loads(CONTENT_PATH.read_text())


# ---------------------------------------------------------------------------
# Engine A: Emboss
# ---------------------------------------------------------------------------

def render_precision(data: dict) -> bytes:
    from emboss import Document, TextRun, Citation

    doc = Document(
        title=data.get("title", ""),
        author=data.get("author", ""),
        language="en-US",
        style="academic",
        header_text=data.get("title", ""),
        page_numbers=True,
        tagged=True,
        toc=True,
    )

    for si, section in enumerate(data.get("sections", [])):
        if si > 0:
            doc.page_break()
        doc.heading(section["heading"], level=section.get("level", 1))
        for elem in section.get("elements", []):
            _add_element_precision(doc, elem)

    return doc.render()


def _add_element_precision(doc, elem):
    from emboss import TextRun, Citation

    etype = elem.get("type", "")
    if etype == "paragraph":
        doc.paragraph(elem["text"])
    elif etype == "paragraph_rich":
        runs = [TextRun(r["text"], bold=r.get("bold", False),
                        italic=r.get("italic", False), color=r.get("color"))
                for r in elem.get("runs", [])]
        doc.paragraph(runs)
    elif etype == "bullets":
        doc.bullets(elem["items"])
    elif etype == "table":
        doc.table(headers=elem["headers"], rows=elem["rows"],
                  caption=elem.get("caption"), stripe=elem.get("stripe", False))
    elif etype == "code":
        doc.code_block(code=elem["code"], language=elem.get("language", "text"),
                       line_numbers=True, theme="dark_modern",
                       caption=elem.get("caption"))
    elif etype == "math":
        doc.math(elem["source"], caption=elem.get("caption"))
    elif etype == "callout":
        doc.callout(elem["text"], variant=elem.get("variant", "info"))
    elif etype == "chart":
        doc.chart(chart_type=elem.get("chart_type", "bar"),
                  labels=elem["labels"],
                  values=[float(v) for v in elem["values"]],
                  title=elem.get("title"))
    elif etype == "footnote":
        doc.footnote(elem["text"], marker=elem.get("marker"))
    elif etype == "bibliography":
        citations = [Citation(key=c["key"], authors=c.get("authors", []),
                              title=c.get("title", ""), year=c.get("year", ""),
                              publisher=c.get("publisher"),
                              journal=c.get("journal"), volume=c.get("volume"),
                              pages=c.get("pages"),
                              entry_type=c.get("entry_type", "article"))
                     for c in elem.get("citations", [])]
        doc.bibliography(citations=citations)


# ---------------------------------------------------------------------------
# Engine B: ReportLab
# ---------------------------------------------------------------------------

def render_reportlab(data: dict) -> bytes:
    from reportlab.lib.pagesizes import letter
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import inch
    from reportlab.lib.colors import HexColor, black, white
    from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_JUSTIFY
    from reportlab.platypus import (
        SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
        PageBreak, Preformatted, KeepTogether,
    )
    from io import BytesIO

    buf = BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=letter,
                            topMargin=72, bottomMargin=72,
                            leftMargin=72, rightMargin=72,
                            title=data.get("title", ""),
                            author=data.get("author", ""))

    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle("CustomH1", parent=styles["Heading1"],
                              fontSize=18, spaceAfter=12, spaceBefore=18))
    styles.add(ParagraphStyle("CustomH2", parent=styles["Heading2"],
                              fontSize=14, spaceAfter=10, spaceBefore=14))
    styles.add(ParagraphStyle("CustomBody", parent=styles["Normal"],
                              fontSize=10, leading=14, alignment=TA_JUSTIFY))
    styles.add(ParagraphStyle("CodeStyle", parent=styles["Code"],
                              fontSize=8, leading=10, backColor=HexColor("#1e1e2e"),
                              textColor=white, leftIndent=6, rightIndent=6,
                              spaceBefore=6, spaceAfter=6))
    styles.add(ParagraphStyle("BulletStyle", parent=styles["Normal"],
                              fontSize=10, leading=14, bulletIndent=18,
                              leftIndent=36))
    styles.add(ParagraphStyle("CaptionStyle", parent=styles["Normal"],
                              fontSize=9, leading=11, textColor=HexColor("#666666"),
                              alignment=TA_CENTER, spaceAfter=8))
    styles.add(ParagraphStyle("CalloutStyle", parent=styles["Normal"],
                              fontSize=9, leading=12, leftIndent=12,
                              rightIndent=12, spaceBefore=6, spaceAfter=6,
                              backColor=HexColor("#eff6ff")))
    styles.add(ParagraphStyle("FootnoteStyle", parent=styles["Normal"],
                              fontSize=8, leading=10, textColor=HexColor("#666666")))
    styles.add(ParagraphStyle("BibStyle", parent=styles["Normal"],
                              fontSize=9, leading=11, leftIndent=24,
                              firstLineIndent=-24))

    story = []
    story.append(Paragraph(data.get("title", ""), styles["Title"]))
    if data.get("author"):
        story.append(Paragraph(data["author"], styles["Normal"]))
    story.append(Spacer(1, 12))

    for si, section in enumerate(data.get("sections", [])):
        if si > 0:
            story.append(PageBreak())

        level = section.get("level", 1)
        hstyle = "CustomH1" if level == 1 else "CustomH2"
        story.append(Paragraph(section["heading"], styles[hstyle]))

        for elem in section.get("elements", []):
            _add_element_reportlab(story, elem, styles)

    doc.build(story)
    return buf.getvalue()


def _add_element_reportlab(story, elem, styles):
    from reportlab.platypus import Paragraph, Spacer, Table, TableStyle, Preformatted
    from reportlab.lib.colors import HexColor, black
    from reportlab.lib.units import inch

    etype = elem.get("type", "")

    if etype == "paragraph":
        story.append(Paragraph(_rl_escape(elem["text"]), styles["CustomBody"]))
        story.append(Spacer(1, 6))

    elif etype == "paragraph_rich":
        parts = []
        for r in elem.get("runs", []):
            text = _rl_escape(r["text"])
            if r.get("bold"):
                text = f"<b>{text}</b>"
            if r.get("italic"):
                text = f"<i>{text}</i>"
            if r.get("color"):
                text = f'<font color="#{r["color"]}">{text}</font>'
            parts.append(text)
        story.append(Paragraph("".join(parts), styles["CustomBody"]))
        story.append(Spacer(1, 6))

    elif etype == "bullets":
        for item in elem["items"]:
            story.append(Paragraph(
                f"<bullet>&bull;</bullet> {_rl_escape(item)}",
                styles["BulletStyle"]))
        story.append(Spacer(1, 6))

    elif etype == "table":
        headers = elem["headers"]
        rows = elem["rows"]
        table_data = [headers] + rows
        t = Table(table_data, repeatRows=1)
        style_cmds = [
            ("BACKGROUND", (0, 0), (-1, 0), HexColor("#f0f0f0")),
            ("TEXTCOLOR", (0, 0), (-1, 0), black),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
            ("LEADING", (0, 0), (-1, -1), 12),
            ("GRID", (0, 0), (-1, -1), 0.5, HexColor("#cccccc")),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ("LEFTPADDING", (0, 0), (-1, -1), 6),
            ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ]
        if elem.get("stripe"):
            for i in range(1, len(table_data)):
                if i % 2 == 0:
                    style_cmds.append(
                        ("BACKGROUND", (0, i), (-1, i), HexColor("#fafafa")))
        t.setStyle(TableStyle(style_cmds))
        story.append(t)
        if elem.get("caption"):
            story.append(Paragraph(elem["caption"], styles["CaptionStyle"]))
        story.append(Spacer(1, 8))

    elif etype == "code":
        code = elem["code"]
        story.append(Preformatted(code, styles["CodeStyle"]))
        if elem.get("caption"):
            story.append(Paragraph(elem["caption"], styles["CaptionStyle"]))
        story.append(Spacer(1, 8))

    elif etype == "math":
        story.append(Paragraph(
            f'<para alignment="center"><i>{_rl_escape(elem["source"])}</i></para>',
            styles["CustomBody"]))
        if elem.get("caption"):
            story.append(Paragraph(elem["caption"], styles["CaptionStyle"]))

    elif etype == "callout":
        story.append(Paragraph(_rl_escape(elem["text"]), styles["CalloutStyle"]))
        story.append(Spacer(1, 6))

    elif etype == "chart":
        story.append(Paragraph(
            f'<b>{_rl_escape(elem.get("title", "Chart"))}</b>',
            styles["CustomBody"]))
        labels = elem.get("labels", [])
        values = elem.get("values", [])
        for l, v in zip(labels, values):
            story.append(Paragraph(f"  {_rl_escape(str(l))}: {v}", styles["CustomBody"]))
        story.append(Spacer(1, 8))

    elif etype == "footnote":
        marker = elem.get("marker", "*")
        story.append(Paragraph(
            f"<super>{_rl_escape(marker)}</super> {_rl_escape(elem['text'])}",
            styles["FootnoteStyle"]))

    elif etype == "bibliography":
        story.append(Paragraph("References", styles["CustomH2"]))
        for i, c in enumerate(elem.get("citations", []), 1):
            authors = ", ".join(c.get("authors", []))
            title = c.get("title", "")
            year = c.get("year", "")
            venue = c.get("journal") or c.get("publisher", "")
            text = f'[{i}] {_rl_escape(authors)}, "{_rl_escape(title)},"'
            if venue:
                text += f" <i>{_rl_escape(venue)}</i>,"
            text += f" {_rl_escape(year)}."
            story.append(Paragraph(text, styles["BibStyle"]))
        story.append(Spacer(1, 8))


def _rl_escape(text: str) -> str:
    return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def _fpdf2_safe(text: str) -> str:
    out = []
    for ch in text:
        if ord(ch) < 256:
            out.append(ch)
        else:
            out.append("?")
    return "".join(out)


# ---------------------------------------------------------------------------
# Engine C: WeasyPrint (HTML -> PDF)
# ---------------------------------------------------------------------------

def render_weasyprint(data: dict) -> bytes:
    import weasyprint

    html_path = OUTPUT / "llm_generated.html"
    if not html_path.exists():
        print("  HTML file not found, skipping WeasyPrint")
        return b""

    html_content = html_path.read_text()
    pdf = weasyprint.HTML(string=html_content).write_pdf()
    return pdf


# ---------------------------------------------------------------------------
# Engine D: FPDF2
# ---------------------------------------------------------------------------

def render_fpdf2(data: dict) -> bytes:
    from fpdf import FPDF

    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=72)
    pdf.set_margins(72, 72, 72)
    pdf.add_page()

    pdf.set_font("Helvetica", "B", 18)
    pdf.cell(0, 12, data.get("title", ""), new_x="LMARGIN", new_y="NEXT")
    if data.get("author"):
        pdf.set_font("Helvetica", "I", 10)
        pdf.cell(0, 8, data["author"], new_x="LMARGIN", new_y="NEXT")
    pdf.ln(8)

    for si, section in enumerate(data.get("sections", [])):
        if si > 0:
            pdf.add_page()

        level = section.get("level", 1)
        size = 16 if level == 1 else 13
        pdf.set_font("Helvetica", "B", size)
        pdf.cell(0, size * 0.8, section["heading"], new_x="LMARGIN", new_y="NEXT")
        pdf.ln(4)

        for elem in section.get("elements", []):
            _add_element_fpdf2(pdf, elem)

    return bytes(pdf.output())


def _add_element_fpdf2(pdf, elem):
    from fpdf import FPDF

    etype = elem.get("type", "")
    page_width = pdf.w - pdf.l_margin - pdf.r_margin

    if etype == "paragraph":
        pdf.set_font("Helvetica", "", 10)
        pdf.multi_cell(0, 5, _fpdf2_safe(elem["text"]))
        pdf.ln(3)

    elif etype == "paragraph_rich":
        pdf.set_font("Helvetica", "", 10)
        for r in elem.get("runs", []):
            style = ""
            if r.get("bold"):
                style += "B"
            if r.get("italic"):
                style += "I"
            pdf.set_font("Helvetica", style, 10)
            pdf.write(5, _fpdf2_safe(r["text"]))
        pdf.ln(8)

    elif etype == "bullets":
        pdf.set_font("Helvetica", "", 10)
        for item in elem["items"]:
            pdf.cell(12, 5, "-")
            pdf.multi_cell(page_width - 12, 5, _fpdf2_safe(item))
            pdf.ln(1)
        pdf.ln(3)

    elif etype == "table":
        headers = elem["headers"]
        rows = elem["rows"]
        col_count = len(headers)
        col_w = page_width / col_count

        pdf.set_font("Helvetica", "B", 9)
        for h in headers:
            pdf.cell(col_w, 7, _fpdf2_safe(str(h)[:30]), border=1)
        pdf.ln()

        pdf.set_font("Helvetica", "", 9)
        for row in rows:
            for i, cell in enumerate(row):
                pdf.cell(col_w, 6, _fpdf2_safe(str(cell)[:30]), border=1)
            pdf.ln()

        if elem.get("caption"):
            pdf.set_font("Helvetica", "I", 8)
            pdf.cell(0, 5, elem["caption"], new_x="LMARGIN", new_y="NEXT")
        pdf.ln(4)

    elif etype == "code":
        pdf.set_font("Courier", "", 8)
        pdf.set_fill_color(30, 30, 46)
        pdf.set_text_color(205, 214, 244)
        for line in elem["code"].split("\n"):
            pdf.cell(0, 4, _fpdf2_safe(line[:100]), new_x="LMARGIN", new_y="NEXT", fill=True)
        pdf.set_text_color(0, 0, 0)
        if elem.get("caption"):
            pdf.set_font("Helvetica", "I", 8)
            pdf.cell(0, 5, elem["caption"], new_x="LMARGIN", new_y="NEXT")
        pdf.ln(4)

    elif etype == "math":
        pdf.set_font("Helvetica", "I", 11)
        pdf.cell(0, 8, _fpdf2_safe(elem["source"]), new_x="LMARGIN", new_y="NEXT", align="C")
        if elem.get("caption"):
            pdf.set_font("Helvetica", "I", 8)
            pdf.cell(0, 5, elem["caption"], new_x="LMARGIN", new_y="NEXT", align="C")
        pdf.ln(3)

    elif etype == "callout":
        pdf.set_fill_color(239, 246, 255)
        pdf.set_font("Helvetica", "", 9)
        pdf.multi_cell(0, 5, _fpdf2_safe(elem["text"]), fill=True)
        pdf.set_fill_color(255, 255, 255)
        pdf.ln(4)

    elif etype == "chart":
        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(0, 7, elem.get("title", "Chart"), new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "", 9)
        for l, v in zip(elem.get("labels", []), elem.get("values", [])):
            pdf.cell(0, 5, f"  {l}: {v}", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(4)

    elif etype == "footnote":
        pdf.set_font("Helvetica", "", 8)
        marker = elem.get("marker", "*")
        pdf.cell(0, 4, _fpdf2_safe(f"[{marker}] {elem['text']}"), new_x="LMARGIN", new_y="NEXT")

    elif etype == "bibliography":
        pdf.set_font("Helvetica", "B", 13)
        pdf.cell(0, 10, "References", new_x="LMARGIN", new_y="NEXT")
        for i, c in enumerate(elem.get("citations", []), 1):
            pdf.set_font("Helvetica", "", 9)
            authors = ", ".join(c.get("authors", []))
            title = c.get("title", "")
            year = c.get("year", "")
            venue = c.get("journal") or c.get("publisher", "")
            ref = f'[{i}] {authors}, "{title},"'
            if venue:
                ref += f" {venue},"
            ref += f" {year}."
            pdf.multi_cell(0, 4, _fpdf2_safe(ref))
            pdf.ln(2)


# ---------------------------------------------------------------------------
# Report
# ---------------------------------------------------------------------------

def analyze_pdf(pdf_bytes: bytes, label: str) -> dict:
    features = {
        "label": label,
        "size_bytes": len(pdf_bytes),
        "size_kb": round(len(pdf_bytes) / 1024, 1),
        "valid": pdf_bytes[:5] == b"%PDF-",
        "tagged": b"/StructTreeRoot" in pdf_bytes,
        "has_toc": b"/Outlines" in pdf_bytes,
        "has_metadata": b"/Title" in pdf_bytes,
        "has_lang": b"/Lang" in pdf_bytes,
        "font_count": pdf_bytes.count(b"/Font"),
        "page_count": pdf_bytes.count(b"/Type /Page") - pdf_bytes.count(b"/Type /Pages"),
    }
    return features


def print_comparison(results: list[dict]) -> str:
    lines = []
    lines.append("=" * 78)
    lines.append("  PDF ENGINE COMPARISON REPORT")
    lines.append("=" * 78)
    lines.append("")

    col_w = 20
    header = f"{'Feature':<25}"
    for r in results:
        header += f"{r['label']:>{col_w}}"
    lines.append(header)
    lines.append("-" * len(header))

    fields = [
        ("File Size", lambda r: f"{r['size_kb']} KB"),
        ("Valid PDF", lambda r: "Yes" if r["valid"] else "No"),
        ("PDF/UA Tagged", lambda r: "Yes" if r["tagged"] else "No"),
        ("Table of Contents", lambda r: "Yes" if r["has_toc"] else "No"),
        ("Document Metadata", lambda r: "Yes" if r["has_metadata"] else "No"),
        ("Language Tag", lambda r: "Yes" if r["has_lang"] else "No"),
        ("Font References", lambda r: str(r["font_count"])),
        ("Page Count", lambda r: str(r["page_count"])),
    ]

    for name, fn in fields:
        row = f"{name:<25}"
        for r in results:
            row += f"{fn(r):>{col_w}}"
        lines.append(row)

    lines.append("-" * len(header))

    feature_matrix = [
        "Vector Charts",
        "Math Rendering",
        "Code Highlighting",
        "Deterministic Output",
        "Accessibility Tags",
        "Zero Heavy Deps",
    ]
    engine_features = {
        "Emboss": [True, True, True, True, True, True],
        "ReportLab": [True, False, False, False, False, False],
        "WeasyPrint": [False, False, False, False, False, False],
        "FPDF2": [False, False, False, False, False, False],
    }

    lines.append("")
    lines.append(f"{'Capability':<25}", )
    for r in results:
        lines[-1] += f"{r['label']:>{col_w}}"
    lines.append("-" * len(lines[-1]))

    for i, feat in enumerate(feature_matrix):
        row = f"{feat:<25}"
        for r in results:
            has = engine_features.get(r["label"], [False] * 6)
            val = has[i] if i < len(has) else False
            row += f"{'Yes':>{col_w}}" if val else f"{'No':>{col_w}}"
        lines.append(row)

    lines.append("")
    lines.append("=" * 78)

    report = "\n".join(lines)
    print(report)
    return report


def main():
    data = load_content()

    engines = [
        ("Emboss", "comparison_precision.pdf", render_precision),
        ("ReportLab", "comparison_reportlab.pdf", render_reportlab),
        ("WeasyPrint", "comparison_weasyprint.pdf", render_weasyprint),
        ("FPDF2", "comparison_fpdf2.pdf", render_fpdf2),
    ]

    results = []
    timings = {}

    for label, filename, renderer in engines:
        print(f"Rendering with {label}...")
        try:
            t0 = time.perf_counter()
            pdf_bytes = renderer(data)
            elapsed = time.perf_counter() - t0
            timings[label] = elapsed

            if pdf_bytes:
                path = OUTPUT / filename
                path.write_bytes(pdf_bytes)
                info = analyze_pdf(pdf_bytes, label)
                info["time_ms"] = round(elapsed * 1000)
                results.append(info)
                print(f"  Done: {info['size_kb']} KB, {info['time_ms']} ms")
            else:
                print(f"  Skipped (no output)")
        except Exception as e:
            print(f"  Error: {e}")

    report = print_comparison(results)

    timing_lines = ["\nRender Times:"]
    for label, ms in sorted(timings.items(), key=lambda x: x[1]):
        timing_lines.append(f"  {label:<20} {ms*1000:>8.0f} ms")
    timing_report = "\n".join(timing_lines)
    print(timing_report)

    report_path = OUTPUT / "comparison_report.txt"
    report_path.write_text(report + "\n" + timing_report + "\n")
    print(f"\nReport saved: {report_path}")
    print(f"PDFs saved in: {OUTPUT}")


if __name__ == "__main__":
    main()
