"""Emboss - constraint-driven PDF generation.

Describe a document; the engine handles layout, typography, and the
PDF/UA structure tree. Output is deterministic: identical input always
produces identical bytes.

    from emboss import Document

    doc = Document(title="Quarterly Report", style="finance")
    doc.heading("Revenue Analysis", level=1)
    doc.paragraph("Revenue increased 12% year over year.")
    doc.table(headers=["Region", "Q3"], rows=[["North", "$2.4M"]])
    doc.save("report.pdf")
"""

from .constraints import (
    ConstraintValidator,
    Issue,
    ValidationError,
    ValidationResult,
)
from .arithmetic import check_table_totals, parse_number
from .spec import (
    Abstract,
    Appendix,
    Author,
    Authors,
    BibliographyBlock,
    BulletList,
    Callout,
    Chart,
    Citation,
    CodeBlock,
    CoverPage,
    Document,
    Footnote,
    Glossary,
    GlossaryEntry,
    HeaderFooter,
    Heading,
    HorizontalRule,
    Image,
    Index,
    LegalFeatures,
    ListOfFigures,
    ListOfTables,
    MathBlock,
    NumberedList,
    PageBreak,
    PageSpec,
    Paragraph,
    PullQuote,
    Series,
    Stat,
    StatTiles,
    SvgBlock,
    Table,
    TableCell,
    TableOfContents,
    TextRun,
)
from .brandkit import BrandKit
from .bibliography import format_citation, format_bibliography
from .code_highlight import tokenize, colorize, THEMES as CODE_THEMES, LANGUAGES
from .math_render import parse_math, MathExpression, render_math
from .colors import (
    ColorTheme,
    resolve_color,
    PALETTES,
    CmykColor,
    SpotColor,
    rgb_to_cmyk,
    parse_cmyk,
)
from .crossref import CrossReferenceIndex
from .diagrams import (
    ArchGroup,
    ArchNode,
    DiagramEdge,
    DiagramNode,
    Entity,
    EntityAttribute,
    Relationship,
    SequenceMessage,
    SequenceParticipant,
    architecture_alt_text,
    architecture_svg_block,
    diagram_alt_text,
    diagram_svg_block,
    er_alt_text,
    er_svg_block,
    layout_diagram,
    render_architecture_svg,
    render_diagram_svg,
    render_er_svg,
    render_sequence_svg,
    sequence_alt_text,
    sequence_svg_block,
)
from .svg import SvgImage, parse_svg, render_svg
from .numbering import AppendixNumberingContext, NumberingContext
from .styles import PRESETS, Style, StyleSheet, apply_brand, resolve_preset
from .typography.font_metrics import FontMetrics, FontRegistry
from .typography.hyphenation import Hyphenator
from .typography.line_breaking import LineBreaker
from .typography.numbers import format_number
from .intelligence import (
    ContentAnalyzer,
    QualityScorer,
    SmartTypography,
    TableIntelligence,
    DocumentTypeDetector,
)
from .slides import slide_document, SlideConfig, SLIDE_16_9, SLIDE_4_3
from .templates import (
    memo,
    report,
    letter,
    invoice,
    academic_paper,
    legal_brief,
    slide_deck,
    data_sheet,
)
from .markdown import parse_markdown, parse_front_matter, FrontMatter
from .nodeid import assign_node_ids, derive_node_id, layout_map_json
from .textmap import TextIndex, Resolution, reconstruct_node_text, text_map_json
from .generate import (
    spec_prompt,
    generate,
    parse_spec_json,
    parse_spec_dict,
    spec_schema,
)
from .recovery import (
    document_from_spec_dict,
    document_to_spec_dict,
    recover_from_attachment,
    recover_from_structure_tree,
    strip_pdf,
)
from .diff import DiffResult, diff_documents, render_redline, word_diff
from .facturx import (
    FacturXMeta,
    Invoice,
    InvoiceLine,
    Party,
    build_cii_xml,
    facturx_attachment,
)
from .writer import RenderResult, render_document
from .manifest import MANIFEST_FILENAME, ReproductionReport, build_manifest, reproduce
from .redaction import (
    RedactionMark,
    RedactionRule,
    apply_redactions,
    decrypt_attachment,
    encrypt_attachment,
    redact_document,
)
from .signing import (
    SignatureField,
    build_acroform,
    build_certifying_signature,
    build_docmdp_reference,
    build_perms_dict,
    build_sig_field_dict,
    build_signature_appearance,
    can_sign,
    sign_pdf,
)
from .amend import (
    Attestation,
    CoverageReport,
    Revision,
    amend_pdf,
    amend_sign,
    coverage_report,
    format_history,
    prepare_signature,
    revision_history,
    verify_amended,
)

try:
    from importlib.metadata import PackageNotFoundError, version as _pkg_version

    __version__ = _pkg_version("emboss-pdf")
except (ImportError, PackageNotFoundError):
    __version__ = "0.4.0"

__all__ = [
    "Document",
    "PageSpec",
    "Heading",
    "Paragraph",
    "BulletList",
    "NumberedList",
    "Table",
    "TableCell",
    "TextRun",
    "Image",
    "Chart",
    "Series",
    "Footnote",
    "Callout",
    "CodeBlock",
    "MathBlock",
    "BibliographyBlock",
    "Citation",
    "SvgBlock",
    "CoverPage",
    "Abstract",
    "Author",
    "Authors",
    "PullQuote",
    "Stat",
    "StatTiles",
    "TableOfContents",
    "ListOfFigures",
    "ListOfTables",
    "PageBreak",
    "HorizontalRule",
    "Appendix",
    "Index",
    "GlossaryEntry",
    "Glossary",
    "LegalFeatures",
    "HeaderFooter",
    "SvgImage",
    "parse_svg",
    "render_svg",
    "DiagramNode",
    "DiagramEdge",
    "layout_diagram",
    "render_diagram_svg",
    "diagram_alt_text",
    "diagram_svg_block",
    "ArchNode",
    "ArchGroup",
    "architecture_alt_text",
    "architecture_svg_block",
    "render_architecture_svg",
    "SequenceParticipant",
    "SequenceMessage",
    "sequence_alt_text",
    "sequence_svg_block",
    "render_sequence_svg",
    "Entity",
    "EntityAttribute",
    "Relationship",
    "er_alt_text",
    "er_svg_block",
    "render_er_svg",
    "NumberingContext",
    "AppendixNumberingContext",
    "format_citation",
    "format_bibliography",
    "tokenize",
    "colorize",
    "CODE_THEMES",
    "LANGUAGES",
    "parse_math",
    "MathExpression",
    "render_math",
    "ColorTheme",
    "resolve_color",
    "PALETTES",
    "CmykColor",
    "SpotColor",
    "rgb_to_cmyk",
    "parse_cmyk",
    "CrossReferenceIndex",
    "Style",
    "StyleSheet",
    "PRESETS",
    "resolve_preset",
    "apply_brand",
    "BrandKit",
    "FontRegistry",
    "FontMetrics",
    "Hyphenator",
    "LineBreaker",
    "format_number",
    "ConstraintValidator",
    "check_table_totals",
    "parse_number",
    "ValidationResult",
    "ValidationError",
    "Issue",
    "slide_document",
    "SlideConfig",
    "SLIDE_16_9",
    "SLIDE_4_3",
    "memo",
    "report",
    "letter",
    "invoice",
    "academic_paper",
    "legal_brief",
    "slide_deck",
    "data_sheet",
    "render_document",
    "RenderResult",
    "parse_markdown",
    "parse_front_matter",
    "FrontMatter",
    "assign_node_ids",
    "derive_node_id",
    "layout_map_json",
    "TextIndex",
    "Resolution",
    "reconstruct_node_text",
    "text_map_json",
    "spec_prompt",
    "generate",
    "parse_spec_json",
    "parse_spec_dict",
    "spec_schema",
    "document_to_spec_dict",
    "document_from_spec_dict",
    "recover_from_attachment",
    "recover_from_structure_tree",
    "strip_pdf",
    "ContentAnalyzer",
    "QualityScorer",
    "SmartTypography",
    "TableIntelligence",
    "DocumentTypeDetector",
    "DiffResult",
    "diff_documents",
    "render_redline",
    "word_diff",
    "Invoice",
    "Party",
    "InvoiceLine",
    "build_cii_xml",
    "facturx_attachment",
    "FacturXMeta",
    "MANIFEST_FILENAME",
    "ReproductionReport",
    "build_manifest",
    "reproduce",
    "RedactionMark",
    "RedactionRule",
    "apply_redactions",
    "decrypt_attachment",
    "encrypt_attachment",
    "redact_document",
    "SignatureField",
    "build_acroform",
    "build_certifying_signature",
    "build_docmdp_reference",
    "build_perms_dict",
    "build_sig_field_dict",
    "build_signature_appearance",
    "can_sign",
    "sign_pdf",
    "Attestation",
    "Revision",
    "CoverageReport",
    "amend_pdf",
    "prepare_signature",
    "amend_sign",
    "revision_history",
    "coverage_report",
    "format_history",
    "verify_amended",
    "__version__",
]
